# Generated by Django 4.2.1 on 2023-09-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('waiting', 'En espera'), ('active', 'Activo'), ('closed', 'Cerrado')], default='waiting', max_length=20),
        ),
    ]
